### PR TITLE
Removed wrong encodings of URLs (fixes #611).

### LINKED ISSUE #611: Wrong URI component decoding
Hi,

I'm trying to use Pannelum with images stored on Firebase Storage, but I'm having weird url decoding from both the JS api and the iframe component.

I've made a repository reproducing the errors described below: https://github.com/gcangussu/pannelum-decoding-bug

You can serve the files of this repository locally to see the errors.

There is also a firebase project with a file stored there for testing:
```
https://firebasestorage.googleapis.com/v0/b/pannellum-escaping-problem.appspot.com/o/Path%2FTo%2FFile%2Falma.jpg?alt=media&token=26371c15-87e8-4dc2-842b-fea688e817ec
```

I can't use this URL without any type of escaping with the pannellum iframe, because if I do this
```html
<iframe width="600" height="400" allowfullscreen style="border-style:none;" src="https://cdn.pannellum.org/2.4/pannellum.htm?panorama=https://firebasestorage.googleapis.com/v0/b/pannellum-escaping-problem.appspot.com/o/Path%2FTo%2FFile%2Falma.jpg?alt=media&token=26371c15-87e8-4dc2-842b-fea688e817ec"></iframe>
```
The `&token=26371[...]` will be considered part of the main url `https://cdn.pannellum[...]`. (See [iframe.html](https://github.com/gcangussu/pannelum-decoding-bug/blob/master/iframe.html))

So I tried using the JS api:
```js
pannellum.viewer('panorama', {
    "type": "equirectangular",
    "panorama": "https://firebasestorage.googleapis.com/v0/b/pannellum-escaping-problem.appspot.com/o/Path%2FTo%2FFile%2Falma.jpg?alt=media&token=26371c15-87e8-4dc2-842b-fea688e817ec"
});
```
~~But then I get this error: (see [js-api.html](https://github.com/gcangussu/pannelum-decoding-bug/blob/master/js-api.html))
js-api-pannellum~~

~~Note that Pannellum is trying to get the wrong URL, the `%252F` parts should be `%2F`. It encoded `%` to `%25`, but it should not do that, it breaks the URL.~~ (see update on following comment.)

I also tried using the iframe, but encoding the image url with `encodeURIComponent` (see [iframe-escaped.html](https://github.com/gcangussu/pannelum-decoding-bug/blob/master/iframe-escaped.html)). But then I have other problem:
iframe-escaped

Now Pannellum is decoding `%252F` to `/`. But it should not do that, it should only decode one time, from `%252F` to `%2F`. You can check the encoded url runnig this on your console
```
>> encodeURIComponent('https://firebasestorage.googleapis.com/v0/b/pannellum-escaping-problem.appspot.com/o/Path%2FTo%2FFile%2Falma.jpg?alt=media&token=26371c15-87e8-4dc2-842b-fea688e817ec');
"https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Fpannellum-escaping-problem.appspot.com%2Fo%2FPath%252FTo%252FFile%252Falma.jpg%3Falt%3Dmedia%26token%3D26371c15-87e8-4dc2-842b-fea688e817ec"
```
It transforms `%2F` to `%252F`, and if we decode it with `decodeURIComponent` we get our URL back:
```
>> decodeURIComponent("https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Fpannellum-escaping-problem.appspot.com%2Fo%2FPath%252FTo%252FFile%252Falma.jpg%3Falt%3Dmedia%26token%3D26371c15-87e8-4dc2-842b-fea688e817ec")
"https://firebasestorage.googleapis.com/v0/b/pannellum-escaping-problem.appspot.com/o/Path%2FTo%2FFile%2Falma.jpg?alt=media&token=26371c15-87e8-4dc2-842b-fea688e817ec"
```

I didn't look yet at Pannellum's implementation and of how it handles URL parameters, but I think it should use the standard compliant `decodeURIComponent` with the iframe component.

To conclude, I think these behaviours ~~with the JS api~~ and with the iframe+`encodeURIComponent` are bugs. I can help fixing them if they are confirmed.

Thank you,
Gabriel

### PR DESCRIPTION
**Pull request by gcangussu**
Fixes #611 

- Fixed double encoding with `encodeURI`.
- Added protection against `javascript:` URLs, which could be used for XSS.
- Changed use of `innerHTML` to `textContent` where it could be exploited for XSS.
- Removed double decoding of URL parameters in standalone module. I think the right approach is to decode each URL parameter isolated.
- Removed unnecessary array by using `location.search`.

### CODE REVIEW

File: src/standalone/standalone.js [hunk 1]
```diff
@@ -10,17 +10,16 @@ function parseURLParameters() {
     var URL;
     if (window.location.hash.length > 0) {
         // Prefered method since parameters aren't sent to server
-        URL = [window.location.hash.slice(1)];
+        URL = window.location.hash.slice(1);
     } else {
-        URL = decodeURI(window.location.href).split('?');
```
Comment (gcangussu) [inline src/standalone/standalone.js]: If we decode the whole URI before extracting the parameters we risk looping through parameters that are from query string variables such as `panorama`. And we will also not get the right URL for `panorama` or other parameter that is a URL.

File: src/js/pannellum.js [hunk 2]
```diff
@@ -392,7 +392,7 @@ function init() {
                 if (xhr.status != 200) {
                     // Display error if image can't be loaded
                     var a = document.createElement('a');
-                    a.href = encodeURI(p);
```
Comment (gcangussu) [inline src/js/pannellum.js]: This breaks the link and misleads the reason of the error to a wrong URL request.

Comment (mpetroff) [reply src/js/pannellum.js]: Can you guarantee that this doesn't introduce the potential for DOM XSS attacks? That's why the encoding was added in the first place. My cursory attempt to demonstrate an attack failed, but I'd like to be more confident that this doesn't introduce an attack vector.

Comment (gcangussu) [reply src/js/pannellum.js]: Good thinking. We need to prevent urls starting with `javascript:` protocol and use `.textContent` instead of `.innerHTML`.

But other types of XSS attacks are a problem only when you're using a template engine on the server. So there is no chance that the browser will get a `<a href="/" onclick=alert('xss')>` when doing `a.href = x`.

Latter we're setting `a.innerHTML` to `a.href`, `a.href` could have HTML tags, so I will change that to `a.textContent = a.href`. Using textContent prevents XSS attacks that could happen with innerHtml ([see rule 6](https://www.owasp.org/index.php/DOM_based_XSS_Prevention_Cheat_Sheet))

Comment (gcangussu) [reply src/js/pannellum.js]: So I took the liberty to fix other places that could suffer from double encoding URLs and also replaced `encodeURI` with a simple sanitizer to prevent `javascript:` URLs.

File: src/js/pannellum.js [hunk 3]
```diff
@@ -1971,7 +1971,16 @@ function processOptions(isPreview) {
                 break;
             
             case 'fallback':
-                infoDisplay.errorMsg.innerHTML = '<p>Your browser does not support WebGL.<br><a href="' + encodeURI(config[key]) + '" target="_blank">Click here to view this panorama in an alternative viewer.</a></p>';
```
Comment (gcangussu) [inline src/js/pannellum.js]: This could be a source of XSS without `encodeURI`. So I changed to get the browser protections.

File: src/standalone/standalone.js [hunk 4]
```diff
@@ -1,7 +1,9 @@
 function anError(error) {
     var errorMsg = document.createElement('div');
     errorMsg.className = 'pnlm-info-box';
-    errorMsg.innerHTML = '<p>' + error + '</p>';
```
Comment (gcangussu) [inline src/standalone/standalone.js]: I also modified here to avoid XSS.

**Comment by mpetroff** [comment]
The XSS protection seems robust now. Thanks!

**Comment by kaYcee** [comment]
We encountered an issue with our Google Cloud Storage links. Google signs image urls and appends the signature to the download link to ensure authenticity. This results in a mixture of URI-encoded and -decoded parts, e.g. `https://storage.googleapis.com/abcde/images%2Fpanoramas%2Fmypicture.jpg?GoogleAccessId=abcde%40appspot.gserviceaccount.com&Expires=16700323200&Signature=AI8iu9zev1xz6Qt%2BeqXk4%3D%3D...`. Up to now, this hasn't been a problem. But since Pannellum uses `encodeURI()` everywhere, either the front part of the url or its signature gets destroyed. There is no way we can feed it with a proper url, meaning `decodeURI()` prior to the call is not of much help here. 

The only workaround we came up with so far was replacing all occurances of `encodeURI()` with a non-altering version. Is there a way to make the encoding optional like the `escapeHTML` parameter value?

**Comment by gcangussu** [comment]
@kaYcee I had a very similar problem, you should be good once this gets released.
